language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - pip install mock --use-mirrors
  - pip install Django --use-mirrors
  - pip install git+git://github.com/gears/gears.git --use-mirrors
  - pip install . --use-mirrors
script: make test
